"""file assets v1

Revision ID: 21feaf01108d
Revises: a1d870aaa2b8
Create Date: 2025-11-07 18:07:50.619929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21feaf01108d'
down_revision = 'a1d870aaa2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('DOCUMENT', 'PHOTO', name='file_kind'), nullable=False),
    sa.Column('photo_phase', sa.Enum('BEFORE', 'AFTER', name='photo_phase'), nullable=True),
    sa.Column('photo_order', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_assets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_photo_phase'), ['photo_phase'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_assets_photo_phase'))
        batch_op.drop_index(batch_op.f('ix_file_assets_patient_id'))
        batch_op.drop_index(batch_op.f('ix_file_assets_kind'))

    op.drop_table('file_assets')
    # ### end Alembic commands ###
