"""patients v1

Revision ID: a1d870aaa2b8
Revises: fb59c0c266f5
Create Date: 2025-11-07 18:02:43.746919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d870aaa2b8'
down_revision = 'fb59c0c266f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('FEMALE', 'MALE', 'OTHER', name='sex_enum'), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('past_history', sa.String(length=2000), nullable=True),
    sa.Column('allergies', sa.String(length=2000), nullable=True),
    sa.Column('treatments_of_interest', sa.String(length=2000), nullable=True),
    sa.Column('privacy_notice_accepted', sa.Boolean(), nullable=False),
    sa.Column('informed_consent_accepted', sa.Boolean(), nullable=False),
    sa.Column('emergency_full_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_phone', sa.String(length=30), nullable=True),
    sa.Column('emergency_relation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_date_of_birth'), ['date_of_birth'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_sex'), ['sex'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_sex'))
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_last_name'))
        batch_op.drop_index(batch_op.f('ix_patients_first_name'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))
        batch_op.drop_index(batch_op.f('ix_patients_date_of_birth'))

    op.drop_table('patients')
    # ### end Alembic commands ###
