"""appointments v1

Revision ID: d2f28fee388d
Revises: efcd4fe9bba4
Create Date: 2025-11-07 18:50:38.719006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f28fee388d'
down_revision = 'efcd4fe9bba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'NO_SHOW', 'COMPLETED', name='appointment_status'), nullable=False),
    sa.Column('appt_type', sa.Enum('CONSULTA', 'CONTROL', 'PROCEDIMIENTO', 'OTRO', name='appointment_type'), nullable=False),
    sa.Column('treatment', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_appt_type'), ['appt_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_professional_id'), ['professional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_start_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_professional_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_end_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_appt_type'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
